"""
Motor Data Loader

Utility to load motor data from config files and provide thrust/mass functions.
Works with configs generated by generate_motor_config.py that include thrust curve data.
"""

import numpy as np
from scipy import interpolate
from typing import Dict, Any
import yaml


class Motor:
    """Motor with thrust curve data from config file"""

    def __init__(self, motor_config: Dict[str, Any]):
        """
        Initialize motor from config dictionary.

        Args:
            motor_config: The 'motor' section from a config YAML file
        """
        # Basic info
        self.name = motor_config.get("name", "unknown")
        self.manufacturer = motor_config.get("manufacturer", "Unknown")
        self.designation = motor_config.get("designation", "Unknown")

        # Physical properties (convert to SI units)
        self.diameter = motor_config.get("diameter_mm", 54) / 1000  # mm to m
        self.length = motor_config.get("length_mm", 200) / 1000  # mm to m
        self.total_mass = motor_config.get("total_mass_g", 1000) / 1000  # g to kg
        self.propellant_mass = (
            motor_config.get("propellant_mass_g", 500) / 1000
        )  # g to kg
        self.case_mass = motor_config.get("case_mass_g", 500) / 1000  # g to kg

        # Performance
        self.impulse_class = motor_config.get("impulse_class", "K")
        self.total_impulse = motor_config.get("total_impulse_Ns", 1500)
        self.average_thrust = motor_config.get("avg_thrust_N", 400)
        self.max_thrust = motor_config.get("max_thrust_N", 600)
        self.burn_time = motor_config.get("burn_time_s", 3.0)

        # Thrust curve
        thrust_curve = motor_config.get("thrust_curve", {})
        self.time_points = np.array(thrust_curve.get("time_s", [0, 1]))
        self.thrust_points = np.array(thrust_curve.get("thrust_N", [0, 0]))

        # Thrust multiplier for sensitivity testing
        self.thrust_multiplier = motor_config.get("thrust_multiplier", 1.0)

        # Create interpolation function for thrust lookup
        self._setup_interpolators()

    def _setup_interpolators(self):
        """Setup interpolation functions for smooth thrust and mass lookup"""
        # Thrust interpolator
        if len(self.time_points) > 1:
            self.thrust_interpolator = interpolate.interp1d(
                self.time_points,
                self.thrust_points * self.thrust_multiplier,
                kind="linear",
                bounds_error=False,
                fill_value=0.0,
            )
        else:
            # Fallback for missing data
            self.thrust_interpolator = lambda t: 0.0

    def get_thrust(self, time: float) -> float:
        """
        Get thrust at given time.

        Args:
            time: Time in seconds

        Returns:
            Thrust in Newtons
        """
        if time < 0 or time > self.burn_time:
            return 0.0
        return float(self.thrust_interpolator(time))

    def get_mass(self, time: float) -> float:
        """
        Get motor mass at given time (assumes linear propellant burn).

        Args:
            time: Time in seconds

        Returns:
            Mass in kg
        """
        if time <= 0:
            return self.total_mass
        elif time >= self.burn_time:
            return self.case_mass
        else:
            # Linear approximation of propellant consumption
            burn_fraction = time / self.burn_time
            remaining_prop = self.propellant_mass * (1 - burn_fraction)
            return self.case_mass + remaining_prop

    def get_mass_flow_rate(self, time: float) -> float:
        """
        Get approximate mass flow rate at given time.

        Args:
            time: Time in seconds

        Returns:
            Mass flow rate in kg/s
        """
        if time <= 0 or time >= self.burn_time:
            return 0.0

        # For more accuracy, could compute dm/dt from thrust
        # Assuming constant specific impulse
        if self.total_impulse > 0 and self.propellant_mass > 0:
            exhaust_velocity = self.total_impulse / self.propellant_mass
            thrust = self.get_thrust(time)
            return thrust / exhaust_velocity if exhaust_velocity > 0 else 0.0
        else:
            # Linear approximation
            return self.propellant_mass / self.burn_time

    def __repr__(self):
        return (
            f"Motor({self.manufacturer} {self.designation}, "
            f"{self.impulse_class}-class, {self.total_impulse:.1f} N·s)"
        )


def load_motor_from_config(config_path: str) -> Motor:
    """
    Load motor from a config YAML file.

    Args:
        config_path: Path to config YAML file

    Returns:
        Motor object

    Example:
        >>> motor = load_motor_from_config('configs/aerotech_k550w_easy.yaml')
        >>> thrust = motor.get_thrust(1.0)
        >>> mass = motor.get_mass(1.0)
    """
    with open(config_path, "r") as f:
        config = yaml.safe_load(f)

    motor_config = config.get("motor", {})
    return Motor(motor_config)


def load_motor_from_dict(config: Dict[str, Any]) -> Motor:
    """
    Load motor from a config dictionary.

    Args:
        config: Config dictionary (entire config, not just motor section)

    Returns:
        Motor object
    """
    motor_config = config.get("motor", {})
    return Motor(motor_config)


# Example usage
if __name__ == "__main__":
    import sys

    if len(sys.argv) > 1:
        config_path = sys.argv[1]
        motor = load_motor_from_config(config_path)

        print(f"Loaded: {motor}")
        print(f"\nMotor Specifications:")
        print(f"  Manufacturer: {motor.manufacturer}")
        print(f"  Designation: {motor.designation}")
        print(f"  Class: {motor.impulse_class}")
        print(f"  Total Impulse: {motor.total_impulse:.1f} N·s")
        print(f"  Average Thrust: {motor.average_thrust:.1f} N")
        print(f"  Max Thrust: {motor.max_thrust:.1f} N")
        print(f"  Burn Time: {motor.burn_time:.2f} s")
        print(f"  Total Mass: {motor.total_mass * 1000:.1f} g")
        print(f"  Propellant Mass: {motor.propellant_mass * 1000:.1f} g")
        print(f"  Thrust Curve: {len(motor.time_points)} data points")

        print(f"\nThrust Profile:")
        for t in [0, 0.5, 1.0, 2.0, motor.burn_time]:
            if t <= motor.burn_time:
                thrust = motor.get_thrust(t)
                mass = motor.get_mass(t)
                print(f"  t={t:.1f}s: {thrust:.1f}N thrust, {mass*1000:.1f}g mass")
    else:
        print("Usage: python motor_loader.py <config.yaml>")
        print("Example: python motor_loader.py configs/aerotech_k550w_easy.yaml")
